//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace visionIngPrueba
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        public int CustomerID { get; set; }
        public Nullable<int> CustomerNumIde { get; set; }
        public string CustomerTypeIde { get; set; }
        public string CustomerName { get; set; }
        public string CustomerLastName { get; set; }
        public Nullable<System.DateTime> CustomerBirthDate { get; set; }
        public Nullable<int> CustomerAge { get; set; }
        public string CustomerEmail { get; set; }
    }
}
